### ISSUE TITLE
Simple Gallery cannot be updated

### ISSUE THREAD

**Issue by FabianOvrWrt** [ArrowOS/android_packages_apps_ArrowPrebuilts#2]
It is likely due to a difference in the package signature, and since Simple Calendar is a paid app, I can't confirm if it is or it isn't affected. Oddly enough, this doesn't apply to Duckduckgo, which updates with no issues.

![Screenshot_20210608-005824](https://user-images.githubusercontent.com/6712155/121130961-bc4c5980-c7f4-11eb-9306-63c115c32dba.png)

**Comment by justks** [comment]
Not the place to open issues, but yes package signature is different we use GitHub releases which is adfree and has more features than the playstore free edition I believe. So, yes it cannot be updated from Playstore and its known. We can't do anything about it.
You might have to remove it from system (requires: root access) to install the playstore version
Thanks

**Comment by FabianOvrWrt** [comment]
Oh, ok. Flashing the git version actually worked as it is the same signature as your package :+1: 
Thank you for the info.
